import React from "react";
export const OPEN_SIDE_CART = "OPEN_SIDE_CART";
export const CLOSE_SIDE_CART = "CLOSE_SIDE_CART";
export const TOGGLE_SIDE_CART = "TOGGLE_SIDE_CART";
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
//WHATSAPP
export const OPEN_SIDE_CART_WHATSAPP = "OPEN_SIDE_CART_WHATSAPP";
export const CLOSE_SIDE_CART_WHATSAPP = "CLOSE_SIDE_CART_WHATSAPP";
export const TOGGLE_SIDE_CART_WHATSAPP = "TOGGLE_SIDE_CART_WHATSAPP";
export const TOGGLE_SIDE_BAR_WHATSAPP = "TOGGLE_SIDE_BAR_WHATSAPP";
export const CLOSE_SIDEBAR_WHATSAPP = "CLOSE_SIDEBAR_WHATSAPP";
